### ISSUE TITLE
Release 1.4 due to Circe binary incompatibilities

### ISSUE THREAD

**Issue by mdedetrich** [2m/authors#415]
@2m Would it be possible to release this project in its current state as 1.4. The reason why is that the latest release (1.3) is using an older version of Circe 0.13.0 (see https://github.com/2m/authors/pull/215) which is binary incompatible with the current Circe 0.14.x which has already been [updated](https://github.com/2m/authors/blob/main/build.sbt#L23-L24).

```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* io.circe:circe-core_2.12:0.14.6 (early-semver) is selected over {0.13.0}
[error] 	    +- com.github.sbt:sbt-paradox-material-theme:0.7.0 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.14.6)
[error] 	    +- io.circe:circe-jawn_2.12:0.13.0                    (depends on 0.13.0)
[error] 	    +- io.circe:circe-generic_2.12:0.13.0                 (depends on 0.13.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:90)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* io.circe:circe-core_2.12:0.14.6 (early-semver) is selected over {0.13.0}
[error] 	    +- com.github.sbt:sbt-paradox-material-theme:0.7.0 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.14.6)
[error] 	    +- io.circe:circe-jawn_2.12:0.13.0                    (depends on 0.13.0)
[error] 	    +- io.circe:circe-generic_2.12:0.13.0                 (depends on 0.13.0)
```

**Comment by 2m** [comment]
Sure thing! Version 1.4 is on its way to Maven Central.
